version: '3.7'
services:
  mysql:
    image: mysql/mysql-server:8.0.31
    ports:
      - '3306:3306'
    volumes:
      - ./artifacts/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=scr_mysql
      - MYSQL_USER=scriper
      - MYSQL_PASSWORD=123
